# Change these first
owner: VisheshPS # Your GitHub organization or username, where this repository lives
repo: UnicornUptime # The name of this repository

sites:
  - name: Unicorn Bot
    url: $https://UnicornMain.visheshps.repl.co
  - name: UnicornMusic
    url: $https://Discord-MusicBot.visheshps.repl.co
  - name: Personal Website
    url: Work In Progress...
  - name: Unicorn Bot Dashboard
    url: Coming Soon..

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /UnicornUptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Unicorn Uptime** is the website where u can see the status of my Unicorn Discord Bots.."
  introMessage: Here u can see the uptime of bot. U will get to know if the bot goes Down.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/VisheshPS/UnicornUptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
